kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: ecointet
    password: 7d5219ab-ee5b-4111-b5f5-21a5623d3a48
    repo: ecointet/harness-webapp-demo
    dockerfile: nginx/Dockerfile
    context: nginx/
    auto_tag: true
    #tags: "3.71"
#- name: docker-api  
#  image: plugins/docker
#  settings:
#    username: ecointet
#    password: 7d5219ab-ee5b-4111-b5f5-21a5623d3a48
#    repo: ecointet/harness-webapp-demo-api
#    dockerfile: nginx/Dockerfile
#    context: nginx/
#    tags: "latest"
